# Generated by Django 5.2.7 on 2025-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("seat_number", "movie")},
        ),
    ]
