databases:
  - name: movie_theater_db
    databaseName: movie_theater_db
    user: movie_theater_user

services:
  - type: web
    name: movie-theater-booking
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn movie_theater_booking.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie_theater_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: movie_theater_booking.production_settings
      - key: PYTHON_VERSION
        value: 3.12.0